/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKHAL_H
#define _MOCKHAL_H

#include "hal.h"

void Mockhal_Init(void);
void Mockhal_Destroy(void);
void Mockhal_Verify(void);




#define SetRegisterValue_Expect(value) SetRegisterValue_CMockExpect(__LINE__, value)
void SetRegisterValue_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned int value);
#define GetRegisterValue_ExpectAndReturn(cmock_retval) GetRegisterValue_CMockExpectAndReturn(__LINE__, cmock_retval)
void GetRegisterValue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int cmock_to_return);

#endif
